### PR TITLE
Workshop paper

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
I don't really understand why Ben's commit is also part of this PR

**Comment by mbudiu-vmw** [comment]
Should we add the pdf to the repo as well?

**Comment by blp** [comment]
> I don't really understand why Ben's commit is also part of this PR

I think it must have been in your history when you committed your patch. It would probably be better to rebase it out before merging, since it will cause confusion in the history otherwise.

**Comment by blp** [comment]
I don't know if you do rebasing much. In case you don't, you can probably fix this up from your worktree by running `git rebase -i origin/main`, then deleting the line with my commit (it is probably the first line) in the editor that pops up, then saving and quitting your editor.

**Review by blp — APPROVED** [review]

**Pull request merged**
